#PROGRAM TO CALCULATE TOTAL NUMBER OF TILES NEEDED TO COVER A FIELD WITH GIVEN  AREA

import math
area_field=int(input("ENTER THE AREA OF FIELD IN METRE SQUARE :"))
area_TILE=int(input("ENTER THE AREA OF TILE IN CENTIMETRE SQUARE :"))
tilesreq=math.ceil(area_field*100*100/area_TILE)
print("TOTAL NUMBER OF TILES REQUIRED ARE:",tilesreq)