#CALCULATE PERCENTAGE OF MARKS BASED ON FIVE SUBJECTS
m1=int(input("ENTER MARKS FOR FIRST SUBJECT:"))
m2=int(input("ENTER MARKS FOR SECOND SUBJECT:"))
m3=int(input("ENTER MARKS FOR THIRD SUBJECT:"))
m4=int(input("ENTER MARKS FOR FOURTH SUBJECT:"))
m5=int(input("ENTER MARKS FOR FIFTH SUBJECT:"))
perc=(m1+m2+m3+m4+m5)*100/500
print("YOUR PERCENTAGE IS :",perc)